---
sudo: required
language: python
python:
  - "3.9"
services:
  - docker
branches:
  only:
    - main
    - develop
install:
  - pip install -r requirements.txt
script:
  - molecule test
  - molecule test --scenario-name pattern-1
  - molecule test --scenario-name pattern-2
  - molecule test --scenario-name pattern-3
  - molecule test --scenario-name pattern-4
notifications:
  email: false
  slack:
    secure: mjp1PclxrAVfmgIZuNiZqirmqgHgA0Bjt6vBB8NdO7wviRjKYsq1a6+vqFfYrdX1aLlCCtMFpCf0ED3c3bEEdeUZWG1CYHNZizSgEAdHi4uP3rHD2XUOR5WZbWw2MbDaf24Lj7qrKGotN4i4snjr1IBz9pKMqfmq4sgxpmmnOSAOqcpB/p11c6FMxwEMvy8b3lh5yxa0qOaWjhZnTOAu4eV6qHZoaUKjznQ3g8kEucE9Lngv3KoW+bc5IG+9Kx6Re0hale375KzN2KWQqKKn0U5IOy1PP9m8Jco34OZAnN1y+NucSdtBm+51eI1mEMn5p7hm3/aZ1BSbMraao0La6DiClTOx8GSw8EhHb0NLdu/tVknK4sQycNCZVvoOw6Rs2c9/Ho8iNkgYzRghDBj78ZDWVRrMwn/uvPcA0n6f7F4oFbxCLNFn8mbbZ5HuqcW9xEFE4V7J4dtmKA9DXDSia6ZxKZV0w6FgydBEdo03xYN15SUy+i3c0yxbPdI3riRrMutdfi496OFkMwrhMhnwSoFhccXCijHGQ+ncTpUEOsptO2MVjD+aGQ0Rh84SC2z8X2ro9Zit3XoRy38fMnLmx92W01KvWqbiYmS1F3PTDhucqhtzRcSBH1zsmBwA59RKKWxT69gmsOw6LzWkF/d0tqDGfpCrAH+oy3yzIKj4Exg=
