---
sudo: required
language: python
python:
  - "3.9"
services:
  - docker
branches:
  only:
    - develop
install:
  - pip install -r requirements.txt
script:
  - molecule test
  - molecule test --scenario-name pattern-1
  - molecule test --scenario-name pattern-2
  - molecule test --scenario-name pattern-3
  - molecule test --scenario-name pattern-4
notifications:
  email: false
  slack:
    secure: FEvpao20s4FVqL0mq7B0SC4Sa/J9KAnMpYHiPKshAn2R/PCwvq7PObGFTSQEqMRc0olTOtucJImQV7NPM2gtG7nTAE/2LVhIvfE7hxpuaKjCub2g/dnm/0ePXNI0qDwJZ0t4fqzQTP8cNT0c+icwhRrK5AQAxm4PQEW+M9Irf1IHRHHRU/Zz2ArXrDhG9nydM7/ji+DPNEA8H6HluszaQl9CBbnIye9qhS8p5blJYX1LOOKK/WAJ+A/2N2Qb6p3yEAM9cAytH2tK/sSczJVTY1ri9hs7ei4aFIOTUBQ444ugH0DIKlQLzCfz0fsepvUW8dEgS1F0bZvnfCg4/wWLmcjfDArJ62qUyDS9+gp05IrCS+GH3+RXgDQB9Z1td1AQ+0ewJZznCHvyK4Gsq/nvUlP9Ap5CifA3CC9/vFCn1uM31bGTFtkefLVu5h6GSxLSHjYgNtMfkaFJTOFBIdH2zsI0+v8uuVwNMwSLkH/Q4c0V4C2tCmECMjPMiZfKWpTQfZ8p3eL82GNmuYyEMi7okayluc68WoV48B+9ltj4Y6lLpnATw1ZR1nLbnxVIEhEDTqDsdjW7uyB1aXNjeZLpjEu8TwQYJMVjAl5Vc+9c/w/9RwmfH/MwQ8ndPNhVWrJ3jq1+YcbnxWvbif8bpLGypxunv2uiSjuGnjc9Q28GDC0=