---
sudo: required
language: python
python:
  - "3.9"
services:
  - docker
branches:
  only:
    - main
    - develop
    - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/
install:
  - pip install -r requirements.txt
script:
  - molecule test
  - molecule test --scenario-name pattern1
  - molecule test --scenario-name pattern2
  - molecule test --scenario-name pattern3
  - molecule test --scenario-name pattern4
  - molecule test --scenario-name pattern5
notifications:
  email: false
  slack:
    secure: mjp1PclxrAVfmgIZuNiZqirmqgHgA0Bjt6vBB8NdO7wviRjKYsq1a6+vqFfYrdX1aLlCCtMFpCf0ED3c3bEEdeUZWG1CYHNZizSgEAdHi4uP3rHD2XUOR5WZbWw2MbDaf24Lj7qrKGotN4i4snjr1IBz9pKMqfmq4sgxpmmnOSAOqcpB/p11c6FMxwEMvy8b3lh5yxa0qOaWjhZnTOAu4eV6qHZoaUKjznQ3g8kEucE9Lngv3KoW+bc5IG+9Kx6Re0hale375KzN2KWQqKKn0U5IOy1PP9m8Jco34OZAnN1y+NucSdtBm+51eI1mEMn5p7hm3/aZ1BSbMraao0La6DiClTOx8GSw8EhHb0NLdu/tVknK4sQycNCZVvoOw6Rs2c9/Ho8iNkgYzRghDBj78ZDWVRrMwn/uvPcA0n6f7F4oFbxCLNFn8mbbZ5HuqcW9xEFE4V7J4dtmKA9DXDSia6ZxKZV0w6FgydBEdo03xYN15SUy+i3c0yxbPdI3riRrMutdfi496OFkMwrhMhnwSoFhccXCijHGQ+ncTpUEOsptO2MVjD+aGQ0Rh84SC2z8X2ro9Zit3XoRy38fMnLmx92W01KvWqbiYmS1F3PTDhucqhtzRcSBH1zsmBwA59RKKWxT69gmsOw6LzWkF/d0tqDGfpCrAH+oy3yzIKj4Exg=
  webhooks: 
    urls:
      - https://galaxy.ansible.com/api/v1/notifications/
    if: tag IS present
    on_success: always
    on_failure: never
    on_start: never
    on_cancel: never
    on_error: never