---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - ../../defaults/main.yml
    - ../../vars/main.yml
    - vars.yml
  tasks:
  - name: "Get OpenSSL version"
    command: "{{ tiomi_openssl_cmd }} version"
    register: tiomi_reg_openssl_current_version
    changed_when: false
    ignore_errors: true
    check_mode: no
    vars:
      - tiomi_openssl_prefix: "{{ tiomi_scenario_openssl_prefix }}"

  - name: "Check OpenSSL version"
    assert:
      that: tiomi_openssl_install_version in tiomi_reg_openssl_current_version.stdout
      fail_msg: "OpenSSL version is not {{ tiomi_openssl_install_version }}"
